numbers = (10, 20, 30, 40, 20, 50, 20)
print("Tuple:", numbers)
count_20 = numbers.count(20)
print("Count of 20 in tuple:", count_20)
index_30 = numbers.index(30)
print("Index of 30 in tuple:", index_30)
print("Length of tuple:", len(numbers))
print("Maximum value:", max(numbers))
print("Minimum value:", min(numbers))
print("Sum of elements:", sum(numbers))
print("Sorted tuple:", sorted(numbers))
numbers_list = list(numbers)
print("Converted to list:", numbers_list)
new_tuple = tuple([5, 15, 25, 35])
print("New tuple using tuple():", new_tuple)
