list2 = [10,20,30,40,50]
print("Original List: ",list2)
list2.append(110)
print("Append Method: ",list2)
list2.copy()
print("Copy Method: ",list2)
list2.count(10)
print("Count Method: ",list2)
list2.extend([120,130,140])
print("Extend Method: ",list2)
list2.index(10)
print("Index Method: ",list2)
list2.insert(1,11)
print("Insert Method: ",list2)
list2.pop()
print("Pop Method: ",list2)
list2.remove(10)
print("Remove Method: ",list2)
list2.reverse()
print("Reverse Method: ",list2)
list2.sort()
print("Sort Method: ",list2)
list2.clear()
print("Clear Method: ",list2)

